; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -I include

board_build.arduino.memory_type = qio_opi
lib_ldf_mode = deep+
lib_extra_dirs = lib

lib_deps = 
    adafruit/Adafruit GPS Library@^1.7.5
    adafruit/Adafruit BNO08x@^1.2.5